"""Task ids of the four standard LIBERO suites inside RLinf's ``libero_130``.

Zero-shot protocol (DIDO / Faster-WAM): RL on standard LIBERO-Spatial,
-Object, -Goal and -10 only (no LIBERO-90, no LIBERO-Plus). RLinf's
``libero_130`` benchmark aggregates every suite in ``benchmark.libero_suites``
order, de-duplicated by task name, so this script recomputes the ids from the
installed LIBERO instead of hard-coding them (expected: 0–29 and 120–129).

    LIBERO_TYPE=standard python scripts/make_libero4_split.py \
        --out configs/splits/libero4_train.yaml
"""

from __future__ import annotations

import argparse
from pathlib import Path

SUITES = ("libero_spatial", "libero_object", "libero_goal", "libero_10")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    from libero.libero import benchmark
    from rlinf.envs.sim.libero.utils import get_benchmark_overridden

    wanted = set()
    for suite_name in SUITES:
        suite = benchmark.get_benchmark_dict()[suite_name]()
        wanted.update(suite.get_task(i).name for i in range(suite.n_tasks))
    all_tasks = get_benchmark_overridden("libero_130")()
    ids = [i for i in range(all_tasks.n_tasks) if all_tasks.get_task(i).name in wanted]
    if len(ids) != len(wanted):
        raise RuntimeError(f"found {len(ids)} of {len(wanted)} tasks in libero_130")
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(
        "# Generated by scripts/make_libero4_split.py (standard LIBERO four suites in libero_130).\n"
        f"task_id_filter: {ids}\n"
    )
    print(f"[libero4] {len(ids)} tasks -> {args.out}: {ids}")


if __name__ == "__main__":
    main()
